/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package readceilodata;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import javax.swing.JFileChooser;
import java.io.File;
//import java.io.FileFilter;
import java.lang.Object;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.commons.lang3.SystemUtils;






/**
 *
 * @author Szabó-Takács Beáta
 */
public class filechooser extends javax.swing.JFrame {

    
    /**
     * Creates new form NewJFrame
     */
    public String filechooserWindow(int i) {
        //String OS = System.getProperty("os.name").toLowerCase();
        String path = "";
        String name ="";
        initComponents();
        int status;
        FileFilter filter = new FileNameExtensionFilter(".his","his");
        
        if(i==0){
            jFileChooser1.setFileFilter(filter);
            jFileChooser1.setDialogType(javax.swing.JFileChooser.OPEN_DIALOG); 
            status = jFileChooser1.showOpenDialog(null);
            if (status == jFileChooser1.APPROVE_OPTION) {
                if(SystemUtils.IS_OS_WINDOWS){
                path = (jFileChooser1.getCurrentDirectory().getAbsolutePath()+ "\\" + jFileChooser1.getSelectedFile().getName());
                }else{
                path = (jFileChooser1.getCurrentDirectory().getAbsolutePath()+ "//" + jFileChooser1.getSelectedFile().getName());
                }
                    
                
            } else if (status == jFileChooser1.CANCEL_OPTION) {
               dispose();
                
            }
        
        }else {jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
            
            status = jFileChooser1.showSaveDialog(null);
            if(SystemUtils.IS_OS_WINDOWS){
            path = (jFileChooser1.getCurrentDirectory().getAbsolutePath()+ "\\" + jFileChooser1.getSelectedFile().getName());}
            else{
            path = (jFileChooser1.getCurrentDirectory().getAbsolutePath()+ "//" + jFileChooser1.getSelectedFile().getName());  
            }
            if (path.endsWith(".nc") == false){
                path = path + ".nc";
            }
        }   
            
        

    dispose();
    return path;
      
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jFileChooser1.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        jFileChooser1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 22, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
